apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: student-csr
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVFNQTRHQTFVRUF3d0hjM1IxWkdWdWRERVFNQTRHQTFVRUNnd0hiR1ZoY201bApjakNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLT1h0UWVaNDJjYUsyNzltTnVCCkpSanZuNGUzWmZINW5CSzZXVzlNSjVERjNFYmhzZWhXWmN5cUt5VXRhNnBORTlINDBhMVpWMDdtVUdOWE1wME4KRWFOSStaaGZhMExZc1hOM3RwN0c3S0pGaCtJbEdaZGNHTUIyL0V2MTBHYTYwQnNHdG0vWFBWOVBxMVJ5ZHlZcgpIWHZSSUpuSmVvWXNkaXVTY2tPbnpFSDRPOWN4ak0veHprTG41SUYyY2Ztbjh1MzJiY2JUNlQwTmFHSGh3RGFaCko5M0R6ZHFuVS9rLzJ1c0pqK2xQSkZvT3FmMDdveldSRlQveDl5UUVuSU1zT3JGZ0tqc25CUnRUOWdIWDU5aFoKcjE4bStZY1FCdDFXdXMrTFNBL2hKVFJIOXE5ZVdmV3I0eng0RFdpVlo5M1BaMEZkeXY1VDFRZWRSVHpmcFZ6eApTYzhDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUF5bGVqRHIzRzNUTk5tR25XR3M4dFhIQUFQCmxiQ0c5dDRNamJITWErdUJPcG53TVlOYjhrbWhLK1RjWnIxcEcxYWxIR2l5aEV6TnpQekNUa3NZaGtlZlErNlUKVHhRTTQ3d29UVnZ3bUI5cGNTTlluNDE2Tk02d1BYZWZLalVuK0p1SHkzNEc4TVBvbS9QU1krbE1SVklaWGtDVgpxajJUWmI0YUYwRlBXcnhDMjQwU2p0bGkxWEgxSnNJL3oyTG01SEhNVEhLV3l3RVJvSEljQkhERGJCVEV1eGpDCkxZay9BdmxKdDZjVnUyS0xxZ1RTR2wwQmtMbVpCN21wRmpTaGRBUlk2SklGVE9NQmo2T1RPQVJQVlBpWVQ0emkKcUxHNDJPejVzU29lQmtxWGdCUzRLR256dE9pb1dUbktVSnErVmphb1VXSTVqazI5cTBBREh5bDIwTnovCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - digital signature
  - key encipherment
  - client auth
